"""
TechCorp Customer Success AI Agent - Locust Load Test Suite

Performance and load testing for the FTE API.

INCUBATION MAPPING:
-------------------
Incubation: No load testing
Production: Locust-based load testing with realistic user scenarios

Test Scenarios:
- Web form submissions (high volume)
- Health check monitoring (low volume)
- Metrics endpoint access (low volume)

Usage:
    locust -f production/tests/load_test.py --host=http://localhost:8000
    # Open http://localhost:8089 in browser
    
    # Headless mode:
    locust -f production/tests/load_test.py --host=http://localhost:8000 \
        --users=100 --spawn-rate=10 --run-time=5m --headless

Author: AI Engineering Team
Version: 1.0.0 (Production)
"""

import random
import string
from locust import HttpUser, task, between, events


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def random_string(length: int = 10) -> str:
    """Generate a random string of specified length."""
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))


def random_email() -> str:
    """Generate a random email address."""
    domains = ["example.com", "test.com", "loadtest.local", "user.io"]
    return f"{random_string(8)}@{random.choice(domains)}"


def random_name() -> str:
    """Generate a random name."""
    first_names = ["John", "Jane", "Bob", "Alice", "Charlie", "Diana", "Eve", "Frank"]
    last_names = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller"]
    return f"{random.choice(first_names)} {random.choice(last_names)}"


# ============================================================================
# USER CLASS 1: Web Form User
# ============================================================================

class WebFormUser(HttpUser):
    """
    Simulates users submitting support forms via web form.
    
    INCUBATION: No load testing
    PRODUCTION: Realistic web form submission load
    
    Configuration:
    - wait_time: 2-10 seconds between requests
    - weight: 3 (3x more likely to be selected than HealthCheckUser)
    
    Tasks:
    - submit_support_form: POST /support/submit with random data
    """
    
    # Wait 2-10 seconds between tasks
    wait_time = between(2, 10)
    
    # Weight: 3x more common than HealthCheckUser
    weight = 3
    
    # Fixed message for load testing
    LOAD_TEST_MESSAGE = (
        "I am experiencing issues with the system during load testing. "
        "This is an automated message generated by Locust for performance testing purposes. "
        "Please investigate the reported issue and provide assistance."
    )
    
    # Valid categories
    CATEGORIES = ["general", "technical", "billing", "feedback", "bug_report"]
    
    @task
    def submit_support_form(self):
        """
        Submit a support form with random data.
        
        INCUBATION: No form submission testing
        PRODUCTION: Realistic load test with randomized data
        
        Generates:
        - Random name (1-10000 characters for stress testing)
        - Random email address
        - Random subject (1-100 characters)
        - Random category from valid list
        - Fixed load test message
        """
        # Generate random name (varying length for stress testing)
        name_length = random.randint(1, 10000)
        name = random_string(name_length) if name_length <= 100 else random_name()
        
        # Generate random email
        email = random_email()
        
        # Generate random subject (1-100 characters)
        subject_length = random.randint(1, 100)
        subject = f"Load Test Issue {random_string(subject_length)}"
        
        # Select random category
        category = random.choice(self.CATEGORIES)
        
        # Prepare form data
        form_data = {
            "name": name,
            "email": email,
            "subject": subject,
            "category": category,
            "message": self.LOAD_TEST_MESSAGE,
            "priority": random.choice(["low", "medium", "high"])
        }
        
        # Submit form
        with self.client.post(
            "/support/submit",
            json=form_data,
            catch_response=True,
            name="/support/submit"
        ) as response:
            # Check response
            if response.status_code == 200:
                # Validate response contains ticket_id
                try:
                    data = response.json()
                    if "ticket_id" in data:
                        response.success()
                    else:
                        response.failure("Missing ticket_id in response")
                except Exception as e:
                    response.failure(f"Invalid JSON response: {str(e)}")
            elif response.status_code == 422:
                # Validation errors are expected with random data
                response.success()
            else:
                response.failure(f"Unexpected status code: {response.status_code}")


# ============================================================================
# USER CLASS 2: Health Check User
# ============================================================================

class HealthCheckUser(HttpUser):
    """
    Simulates monitoring systems checking health and metrics.
    
    INCUBATION: No monitoring load testing
    PRODUCTION: Realistic health check load pattern
    
    Configuration:
    - wait_time: 5-15 seconds between requests
    - weight: 1 (less common than WebFormUser)
    
    Tasks:
    - check_health: GET /health
    - check_metrics: GET /metrics/channels
    """
    
    # Wait 5-15 seconds between tasks
    wait_time = between(5, 15)
    
    # Weight: 1x (less common than WebFormUser)
    weight = 1
    
    @task(2)
    def check_health(self):
        """
        Check the health endpoint.
        
        INCUBATION: No health endpoint
        PRODUCTION: Health check monitoring under load
        
        Weight: 2 (2x more common than check_metrics)
        """
        self.client.get(
            "/health",
            name="/health"
        )
    
    @task(1)
    def check_metrics(self):
        """
        Check the metrics endpoint.
        
        INCUBATION: No metrics endpoint
        PRODUCTION: Metrics monitoring under load
        
        Weight: 1
        """
        self.client.get(
            "/metrics/channels",
            name="/metrics/channels"
        )


# ============================================================================
# LOCUST EVENT HOOKS
# ============================================================================

@events.test_start.add_listener
def on_test_start(environment, **kwargs):
    """
    Called when load test starts.
    
    Args:
        environment: Locust environment
    """
    print("=" * 70)
    print("TechCorp FTE Load Test Starting")
    print("=" * 70)
    print(f"Target Host: {environment.host}")
    print(f"User Classes: WebFormUser (weight=3), HealthCheckUser (weight=1)")
    print("=" * 70)


@events.test_stop.add_listener
def on_test_stop(environment, **kwargs):
    """
    Called when load test stops.
    
    Args:
        environment: Locust environment
    """
    print()
    print("=" * 70)
    print("TechCorp FTE Load Test Complete")
    print("=" * 70)
    
    # Print summary statistics
    stats = environment.stats
    print(f"Total Requests: {stats.total.num_requests}")
    print(f"Total Failures: {stats.total.num_failures}")
    print(f"Failure Rate: {stats.total.fail_ratio * 100:.2f}%")
    print(f"Average Response Time: {stats.total.avg_response_time:.2f}ms")
    print(f"Requests/sec: {stats.total.current_rps:.2f}")
    print("=" * 70)


@events.request.add_listener
def on_request(request_type, name, response_time, response_length, exception, **kwargs):
    """
    Called on each request for custom logging.
    
    Args:
        request_type: HTTP method
        name: Endpoint name
        response_time: Response time in ms
        response_length: Response size in bytes
        exception: Exception if any
    """
    # Log slow requests
    if response_time > 1000:
        print(f"WARNING: Slow request to {name}: {response_time:.0f}ms")


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    # Run with: locust -f load_test.py --host=http://localhost:8000
    import os
    os.system("locust -f production/tests/load_test.py --host=http://localhost:8000")
